language: java
sudo: true
cache:
  directories:
    - $HOME/.m2
script:
  - mvn clean install --errors --batch-mode
env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"
jdk:
  - openjdk8