package miet.rooms.tests.filters;

import lombok.extern.slf4j.Slf4j;
import miet.rooms.Application;
import miet.rooms.api.service.InitializationService;
import miet.rooms.api.web.controller.FilterController;
import miet.rooms.tests.configuration.TestConfig;
import miet.rooms.tests.initializer.PostgreSQLContainerInitializer;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringRunner;

import java.io.IOException;
import java.time.LocalDate;

@RunWith(SpringRunner.class)
@SpringBootTest(classes = {Application.class})
@ContextConfiguration(initializers = {PostgreSQLContainerInitializer.class}, classes = {TestConfig.class})
@Slf4j
public class CycleFilterTest {
    private static boolean initialized = false;

    @Autowired
    private FilterController filterController;

    @Autowired
    private InitializationService initializationService;

    @Before
    public void initializeTables() throws IOException {
        if (!initialized) {
            initializationService.initializeSchedule(LocalDate.now());
            initialized = true;
        }
    }

    @Test
    public void test() {
        for (long periodicityId = 1; periodicityId < 8; periodicityId++) {
            filterController.getFilteredCycleData(null, periodicityId, null, null, null, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, null, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, null, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, null, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, null, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, null, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, null, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, 1L, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, 1L, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, 1L, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, 1L, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, 1L, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, 1L, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, 1L, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, 1L, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, null, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, null, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, null, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, null, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, null, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, null, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, null, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, null, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, 1L, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, 1L, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, 1L, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, 1L, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, 1L, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, 1L, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, 1L, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, 1L, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, null, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, null, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, null, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, null, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, null, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, null, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, null, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, 1L, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, 1L, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, 1L, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, 1L, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, 1L, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, 1L, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, 1L, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, 1L, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, null, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, null, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, null, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, null, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, null, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, null, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, null, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, null, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, 1L, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, 1L, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, 1L, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, 1L, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, 1L, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, 1L, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, 1L, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, 1L, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, null, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, null, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, null, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, null, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, null, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, null, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, null, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, 1L, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, 1L, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, 1L, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, 1L, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, 1L, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, 1L, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, 1L, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, 1L, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, null, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, null, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, null, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, null, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, null, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, null, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, null, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, null, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, 1L, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, 1L, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, 1L, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, 1L, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, 1L, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, 1L, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, 1L, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, 1L, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, null, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, null, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, null, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, null, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, null, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, null, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, null, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, 1L, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, 1L, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, 1L, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, 1L, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, 1L, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, 1L, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, 1L, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, 1L, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, null, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, null, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, null, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, null, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, null, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, null, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, null, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, null, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, 1L, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, 1L, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, 1L, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, 1L, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, 1L, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, 1L, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, 1L, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, 1L, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, null, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, null, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, null, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, null, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, null, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, null, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, null, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, 1L, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, 1L, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, 1L, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, 1L, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, 1L, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, 1L, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, 1L, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, 1L, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, null, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, null, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, null, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, null, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, null, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, null, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, null, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, null, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, 1L, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, 1L, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, 1L, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, 1L, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, 1L, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, 1L, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, 1L, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, 1L, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, null, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, null, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, null, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, null, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, null, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, null, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, null, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, 1L, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, 1L, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, 1L, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, 1L, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, 1L, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, 1L, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, 1L, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, 1L, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, null, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, null, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, null, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, null, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, null, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, null, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, null, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, null, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, 1L, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, 1L, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, 1L, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, 1L, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, 1L, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, 1L, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, 1L, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, 1L, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, null, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, null, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, null, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, null, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, null, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, null, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, null, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, 1L, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, 1L, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, 1L, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, 1L, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, 1L, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, 1L, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, 1L, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, 1L, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, null, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, null, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, null, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, null, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, null, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, null, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, null, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, null, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, 1L, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, 1L, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, 1L, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, 1L, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, 1L, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, 1L, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, 1L, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, 1L, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, null, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, null, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, null, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, null, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, null, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, null, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, null, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, 1L, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, 1L, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, 1L, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, 1L, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, 1L, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, 1L, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, 1L, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, 1L, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, null, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, null, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, null, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, null, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, null, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, null, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, null, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, null, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, 1L, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, 1L, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, 1L, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, 1L, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, 1L, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, 1L, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, 1L, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, 1L, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, null, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, null, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, null, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, null, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, null, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, null, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, null, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, 1L, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, 1L, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, 1L, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, 1L, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, 1L, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, 1L, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, 1L, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, null, 1L, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, null, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, null, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, null, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, null, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, null, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, null, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, null, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, null, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, 1L, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, 1L, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, 1L, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, 1L, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, 1L, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, 1L, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, 1L, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, null, 1L, 1L, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, null, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, null, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, null, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, null, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, null, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, null, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, null, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, 1L, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, 1L, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, 1L, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, 1L, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, 1L, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, 1L, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, 1L, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, null, 1L, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, null, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, null, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, null, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, null, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, null, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, null, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, null, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, null, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, 1L, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, 1L, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, 1L, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, 1L, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, 1L, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, 1L, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, 1L, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(null, periodicityId, 1L, 1L, 1L, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, null, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, null, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, null, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, null, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, null, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, null, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, null, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, 1L, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, 1L, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, 1L, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, 1L, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, 1L, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, 1L, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, 1L, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, null, 1L, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, null, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, null, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, null, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, null, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, null, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, null, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, null, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, null, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, 1L, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, 1L, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, 1L, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, 1L, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, 1L, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, 1L, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, 1L, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, null, 1L, 1L, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, null, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, null, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, null, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, null, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, null, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, null, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, null, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, 1L, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, 1L, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, 1L, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, 1L, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, 1L, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, 1L, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, 1L, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, null, 1L, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, null, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, null, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, null, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, null, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, null, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, null, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, null, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, null, 1L, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, 1L, null, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, 1L, null, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, 1L, null, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, 1L, null, 1L, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, 1L, 1L, null, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, 1L, 1L, null, 1L, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, 1L, 1L, 1L, null, 3L, 0L);
            filterController.getFilteredCycleData(1L, periodicityId, 1L, 1L, 1L, 1L, 1L, 1L, 3L, 0L);
        }
    }
}
